### ISSUE TITLE
4-Cadastro usuário

### ISSUE THREAD

**Issue by Sabrina2106bra** [07Dalmaso/Projeto-PI-3A#13]
criar cadastro para identificação
-nome completo, CPF, email, criar senha, celular

**Comment by 07Dalmaso** [comment]
![Image](https://user-images.githubusercontent.com/79981704/230905473-605c8b2d-1d6d-4ccf-aa69-4362ff0f9db2.png)

**Comment by 07Dalmaso** [comment]
Finalizada
