### ISSUE TITLE
criar cadastro de cartões

### ISSUE THREAD

**Issue by Sabrina2106bra** [07Dalmaso/Projeto-PI-3A#17]
cadastro de cartões no app

**Comment by 07Dalmaso** [comment]
Adicionar Cartão
Nome do Titular *
Lucas Santos Dalmaso
CPF/CNPJ  
047.862.977-15
Número do Cartão *
5594 **** **** 3012
Data de Validade * 
02/27
Código de Verificação *
***
Nome do Cartão
Cartão Santander
Cancelar
Confirmar

**Comment by 07Dalmaso** [comment]
![Image](https://user-images.githubusercontent.com/79981704/230899233-f4efe97e-2a8a-434b-aeaa-d429cded6625.png)
